### ISSUE TITLE
Crash on my android

### ISSUE THREAD

**Issue by mhariri** [vphoners/vphone-dispatcher-app#2]
Getting the following error as soon as I try to "start" the service (uncheck the service and check it again):

```
07-17 00:46:27.382 2406-2433/io.vphone.vphonedispatcher W/dalvikvm: VFY: unable to resolve virtual method 1392: Landroid/os/AsyncTask;.executeOnExecutor (Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Landroid/os/AsyncTask;
07-17 00:46:27.382 2406-2433/io.vphone.vphonedispatcher D/dalvikvm: VFY: replacing opcode 0x6f at 0x0098
07-17 00:46:27.422 2406-2433/io.vphone.vphonedispatcher W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown during Landroid/os/AsyncTask;.<clinit>
07-17 00:46:27.422 2406-2433/io.vphone.vphonedispatcher W/dalvikvm: threadid=45: thread exiting with uncaught exception (group=0x40026160)
07-17 00:46:27.422 2406-2433/io.vphone.vphonedispatcher E/AndroidRuntime: Uncaught handler: thread Thread-24 exiting due to uncaught exception
07-17 00:46:27.442 2406-2433/io.vphone.vphonedispatcher E/AndroidRuntime: java.lang.ExceptionInInitializerError
                                                                              at io.vphone.vphonedispatcher.DispatcherService$Worker.fetchMessagesAndSend(DispatcherService.java:113)
                                                                              at io.vphone.vphonedispatcher.DispatcherService$Worker.run(DispatcherService.java:85)
                                                                              at java.lang.Thread.run(Thread.java:1096)
                                                                           Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                              at android.os.Handler.<init>(Handler.java:121)
                                                                              at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:421)
                                                                              at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:421)
                                                                              at android.os.AsyncTask.<clinit>(AsyncTask.java:152)
                                                                              at io.vphone.vphonedispatcher.DispatcherService$Worker.fetchMessagesAndSend(DispatcherService.java:113) 
                                                                              at io.vphone.vphonedispatcher.DispatcherService$Worker.run(DispatcherService.java:85) 
                                                                              at java.lang.Thread.run(Thread.java:1096) 
07-17 00:46:27.612 2406-2433/io.vphone.vphonedispatcher E/SemcCheckin: Get crash dump level : java.io.FileNotFoundException: /data/semc-checkin/crashdump
```

**Comment by feraswilson** [comment]
I believe you are running the app on an android version older than 4.0 which is why the error are being shown. Will take a look and correct the issue.

**Comment by mhariri** [comment]
Your guess is correct. Android 2.1.1
